/**
 * News ingestion + per-agent takes — PLAN.md 12.24, closing [G34].
 *
 * screens.md screen 23: "Only what moved your book, and what each agent did about it." So this
 * does two things the handoff's three hardcoded cards could not:
 *   1. Pulls REAL headlines from public RSS (no credential required).
 *   2. FILTERS to the user's actual holdings and strategies — a headline about an asset the user
 *      does not touch is not their briefing, it is noise.
 *
 * The agent "take" is generated by the bot runtime under the same voice contract as everything
 * else: the model writes the sentence, the app renders any number.
 */
import { query } from '../db/index.js';
import { THIS_CHAIN } from '../db/chain-scope.js';
import { speak } from '../bot/llm.js';
import { TONE_INSTRUCTIONS, type ToneId } from '../bot/tone.js';
import type { PersonaId } from '../bot/personas.js';

const FEEDS = [
  { url: 'https://www.coindesk.com/arc/outboundfeeds/rss/', tag: 'ON-CHAIN' },
  { url: 'https://cointelegraph.com/rss', tag: 'MACRO' },
];

/** design.md tag chip colours, matching the handoff's fixture. */
const TAG_STYLE: Record<string, { bg: string; fg: string }> = {
  MACRO: { bg: 'rgba(91,147,255,.16)', fg: '#7FA9FF' },
  EARNINGS: { bg: 'rgba(240,190,85,.16)', fg: '#F0BE55' },
  'ON-CHAIN': { bg: 'rgba(73,227,155,.16)', fg: '#49E39B' },
};

export type Headline = { tag: string; title: string; at: number; link: string };

/** Minimal RSS extraction — no XML dependency for two well-formed feeds. */
export function parseRss(xml: string, tag: string, limit = 12): Headline[] {
  const items = xml.split(/<item[\s>]/).slice(1, limit + 1);
  const out: Headline[] = [];
  for (const item of items) {
    const title =
      /<title>\s*(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?\s*<\/title>/.exec(item)?.[1]?.trim() ?? '';
    const link = /<link>\s*(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?\s*<\/link>/.exec(item)?.[1]?.trim() ?? '';
    const date = /<pubDate>([\s\S]*?)<\/pubDate>/.exec(item)?.[1]?.trim();
    if (!title) continue;
    out.push({
      tag,
      title: title.replace(/&amp;/g, '&').replace(/&#\d+;/g, ''),
      at: date ? Date.parse(date) || Date.now() : Date.now(),
      link,
    });
  }
  return out;
}

export async function fetchHeadlines(): Promise<Headline[]> {
  const all: Headline[] = [];
  for (const feed of FEEDS) {
    try {
      const res = await fetch(feed.url, { headers: { accept: 'application/rss+xml, text/xml' } });
      if (!res.ok) continue;
      all.push(...parseRss(await res.text(), feed.tag));
    } catch {
      // One feed being down is not a reason to have no briefing.
    }
  }
  return all.sort((a, b) => b.at - a.at);
}

/** The user's actual exposure: symbols they hold or have a strategy on. */
export async function heldSymbols(walletId: string): Promise<string[]> {
  const rows = await query<{ symbol: string }>(
    `SELECT DISTINCT symbol FROM strategies WHERE wallet_id=$1 AND chain = ${THIS_CHAIN} AND state IN ('live','watch','paused')`,
    [walletId],
  );
  return rows.map((r) => r.symbol);
}

const NAMES: Record<string, string[]> = {
  BTC: ['bitcoin', 'btc'],
  ETH: ['ethereum', 'ether', 'eth'],
  SOL: ['solana', 'sol'],
  XRP: ['xrp', 'ripple'],
  DOGE: ['dogecoin', 'doge'],
  HYPE: ['hyperliquid'],
  AAVE: ['aave'],
  LINK: ['chainlink'],
  TON: ['toncoin', 'the open network'],
};

/** "Only what moved your book" — a headline that names nothing you hold is not your briefing. */
export function relevant(headlines: Headline[], symbols: string[]): (Headline & { symbol: string })[] {
  const out: (Headline & { symbol: string })[] = [];
  for (const h of headlines) {
    const lower = h.title.toLowerCase();
    for (const sym of symbols) {
      const needles = NAMES[sym] ?? [sym.toLowerCase()];
      if (needles.some((n) => lower.includes(n))) {
        out.push({ ...h, symbol: sym });
        break;
      }
    }
  }
  return out;
}

export function relativeTime(at: number, now = Date.now()): string {
  const mins = Math.max(0, Math.round((now - at) / 60_000));
  if (mins < 60) return `${mins}m`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h`;
  return `${Math.round(hours / 24)}d`;
}

const AGENT_FOR: Record<string, PersonaId> = {
  BTC: 'momentum-scout',
  ETH: 'momentum-scout',
  SOL: 'yield-keeper',
  DOGE: 'momentum-scout',
  XRP: 'momentum-scout',
  HYPE: 'momentum-scout',
  AAVE: 'yield-keeper',
  LINK: 'momentum-scout',
  TON: 'yield-keeper',
};

export type BriefingCard = {
  id: string;
  tag: string;
  t: string;
  headline: string;
  /**
   * The agent's comment on this headline, or `null` when there is no model to produce one.
   *
   * Nullable rather than filled in. It used to fall back to the persona's written line, and the
   * result was three unrelated headlines each captioned "Everything is inside its limits. There is
   * nothing for me to do." — the same sentence three times, and on a wallet holding nothing it was
   * also a statement about positions that do not exist. `source` was already reported honestly and
   * the screen rendered `take` regardless, which is the shape of every fallback that reaches a
   * user: the metadata told the truth and the copy did not.
   */
  take: string | null;
  tagBg: string;
  tagFg: string;
  /**
   * Whether a model wrote `take`, or nothing did.
   *
   * Named `'fallback'` until the fallback line was deleted, at which point the value stopped
   * describing anything that exists: there is no fallback copy any more, and `take` is simply
   * `null`. Keeping the old word meant an API response in a project whose central claim is "no
   * fallback data" literally answered `"source":"fallback"` — true of nothing, and the first thing
   * a sceptic greps for.
   */
  source: 'model' | 'none';
  link: string;
};

export async function briefing(walletId: string, tone: ToneId = 'dry'): Promise<BriefingCard[]> {
  const symbols = await heldSymbols(walletId);
  const headlines = await fetchHeadlines();
  // With no positions yet there is no "your book" to filter to, so show the freshest instead —
  // and it is still real news, not a fixture.
  const picked = (symbols.length > 0 ? relevant(headlines, symbols) : []).slice(0, 3);
  const cards = picked.length > 0 ? picked : headlines.slice(0, 3).map((h) => ({ ...h, symbol: '' }));

  const out: BriefingCard[] = [];
  for (const [i, h] of cards.entries()) {
    const persona = AGENT_FOR[h.symbol] ?? 'drawdown-guard';
    const said = await speak({
      persona,
      toneInstruction: TONE_INSTRUCTIONS[tone],
      situation: `A headline says: "${h.title}". Say in one sentence what you did or will do about the user's position, without naming any figure.`,
    });
    const style = TAG_STYLE[h.tag] ?? TAG_STYLE.MACRO!;
    out.push({
      id: `news-${i}`,
      tag: h.tag,
      t: relativeTime(h.at),
      headline: h.title,
      take: said.ok ? said.text : null,
      tagBg: style.bg,
      tagFg: style.fg,
      source: said.ok ? 'model' : 'none',
      link: h.link,
    });
  }
  return out;
}
