/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 */
import type { ActivityEvent } from '../types';

export const activityFixtures: ActivityEvent[] = [
  {
    "id": "act-0",
    "t": "09:41",
    "agent": "Momentum Scout",
    "action": "Bought 4.2 SOL",
    "detail": "Breakout above 20d high · $88.10 avg",
    "amount": "−$370.02",
    "kind": "trade"
  },
  {
    "id": "act-1",
    "t": "09:12",
    "agent": "Momentum Scout",
    "action": "Stop loss moved",
    "detail": "Trailing to −1.0% after +2.4% run",
    "amount": "",
    "kind": "risk"
  },
  {
    "id": "act-2",
    "t": "08:55",
    "agent": "Earnings Desk",
    "action": "Skipped NVDAx",
    "detail": "Spread 0.42% > your 0.25% limit",
    "amount": "",
    "kind": "block"
  },
  {
    "id": "act-3",
    "t": "Yst",
    "agent": "Yield Keeper",
    "action": "Staked 120 SOL",
    "detail": "unlock in 3 days",
    "amount": "+$4.11/day",
    "kind": "yield"
  },
  {
    "id": "act-4",
    "t": "Yst",
    "agent": "Momentum Scout",
    "action": "Take profit hit",
    "detail": "Closed HYPE at +1.8%",
    "amount": "+$44.90",
    "kind": "trade"
  }
];
