/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 */
import type { Agent } from '../types';

export const agentFixtures: Agent[] = [
  {
    "id": "momentum-scout",
    "name": "Momentum Scout",
    "role": "Rides breakouts on liquid majors",
    "metric": "61% win rate",
    "pnl30d": 842,
    "win": 61,
    "trades": 37,
    "c1": "#5B93FF",
    "c2": "#1B44CE"
  },
  {
    "id": "earnings-desk",
    "name": "Earnings Desk",
    "role": "Trades tokenized equity earnings",
    "metric": "54% win rate",
    "pnl30d": 1204,
    "win": 54,
    "trades": 22,
    "c1": "#F0BE55",
    "c2": "#C98518"
  },
  {
    "id": "yield-keeper",
    "name": "Yield Keeper",
    "role": "Moves idle cash into best APY",
    "metric": "Moves idle cash to the best rate",
    "pnl30d": 318,
    "win": 94,
    "trades": 11,
    "c1": "#49E39B",
    "c2": "#12A45F"
  },
  {
    "id": "drawdown-guard",
    "name": "Drawdown Guard",
    "role": "Cuts risk when the book bleeds",
    "metric": "Always on",
    "pnl30d": -96,
    "win": 48,
    "trades": 8,
    "c1": "#B58CFF",
    "c2": "#7A45E0"
  }
];
