/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'simulated' stamped per class so the UI can label synthetic prices.
 */
import type { Alert } from '../types';

export const alertFixtures: Alert[] = [
  {
    "id": "alert-0",
    "name": "SOL above $95",
    "detail": "Price alert · push + agent note",
    "default": true
  },
  {
    "id": "alert-1",
    "name": "NVDAx earnings",
    "detail": "48h before the print",
    "default": true
  },
  {
    "id": "alert-2",
    "name": "Agent hits daily cap",
    "detail": "So you can raise it or stop",
    "default": false
  },
  {
    "id": "alert-3",
    "name": "Drawdown past 5%",
    "detail": "Whole-portfolio circuit breaker",
    "default": false
  },
  {
    "id": "alert-4",
    "name": "Staking unlock ready",
    "detail": "120 SOL, 3 days out",
    "default": false
  }
];
