/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 */
import type { BacktestResult } from '../types';

export const backtestFixtures: BacktestResult[] = [
  {
    "lookback": "30d",
    "ret": 4.2,
    "maxDd": -2.1,
    "sharpe": 1.4,
    "trades": 18,
    "equity": [100.0, 103.64, 109.09, 107.27, 116.36, 120.0, 123.64, 127.27, 134.55, 140.0]
  },
  {
    "lookback": "90d",
    "ret": 11.8,
    "maxDd": -5.4,
    "sharpe": 1.7,
    "trades": 54,
    "equity": [100.0, 103.53, 107.06, 111.76, 109.41, 117.65, 122.35, 124.71, 132.94, 140.0]
  },
  {
    "lookback": "6m",
    "ret": 23.5,
    "maxDd": -9.2,
    "sharpe": 1.2,
    "trades": 121,
    "equity": [100.0, 105.85, 102.93, 111.71, 117.56, 114.63, 123.41, 127.32, 133.17, 140.0]
  },
  {
    "lookback": "1y",
    "ret": 41.9,
    "maxDd": -14.6,
    "sharpe": 1.1,
    "trades": 244,
    "equity": [100.0, 103.4, 108.51, 105.96, 114.47, 119.57, 117.02, 125.53, 132.34, 140.0]
  }
];
