/**
 * Was GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json. **Do not regenerate.**
 *
 * The generator's source is the design prototype's data and is now stale in ways that break the
 * app: it spells the tokenized equities `NVDAx`/`AAPLx`, and the real Base tokens this project
 * trades are `NVDAc`/`AAPLc` — the spelling `STOCKS`, `canonicalSymbol` and the whole equity path
 * depend on. Running `node tools/gen-fixtures.mjs` silently reverts all eight of them and takes
 * the equities integration with it. (Confirmed by doing exactly that, and reverting.)
 *
 * Edit this file directly, and treat it as the source of truth it has become.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 *
 * NO PRICE IS STORED FOR AN INSTRUMENT NOTHING PRICES.
 *
 * The 27 instruments the catalog marks unfed — every commodity, index and pre-IPO name — used to carry the
 * design prototype's prices, shown under a SIMULATED tag: "OPENAI $164.20", "ANTHRP $121.55",
 * "SPACEX $402.70". Prices for companies that have no market, and change figures that also fed
 * the top-movers ranking, so a screen that sorts by "how far they moved" could list a move nobody
 * made. The tag satisfied the letter of "real or labelled" and not its intent — the same argument
 * this codebase already made about a live instrument whose feed times out, which shows a dash
 * rather than the design's price.
 *
 * So they keep what is genuinely catalog — symbol, name, venue tag, colours — and carry no
 * number. One of them still shows a price on screen, and correctly: CoinGecko prices tokenized gold,
 * so XAUT is given a real quote at runtime and stops being unfed. What it no longer has is a stored
 * number to fall back on when that quote does not come. `feed: 'unavailable'` on them means no feed backs this, and the UI says so.
 */
import type { AssetClass } from '../types';

export const assetClasses: AssetClass[] = [
  {
    "id": "crypto",
    "label": "Crypto",
    "note": "Spot prices, live",
    "more": "All crypto",
    "instruments": [
      {
        "sym": "BTC",
        "name": "Bitcoin",
        "tag": "Perp",
        "px": "$66,560",
        "chg": "+0.67%",
        "up": true,
        "c1": "#F7931A",
        "c2": "#B96908",
        "classId": "crypto",
        "feed": "live",
        "mint": "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"
      },
      {
        "sym": "ETH",
        "name": "Ethereum",
        "tag": "Perp",
        "px": "$2,443",
        "chg": "+2.11%",
        "up": true,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "crypto",
        "feed": "live",
        "mint": "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs"
      },
      {
        "sym": "SOL",
        "name": "Solana",
        "tag": "Spot · Perp",
        "px": "$88.32",
        "chg": "+2.40%",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#49E39B",
        "classId": "crypto",
        "feed": "live",
        "mint": "So11111111111111111111111111111111111111112"
      },
      {
        "sym": "XRP",
        "name": "XRP",
        "tag": "Perp",
        "px": "$2.94",
        "chg": "−1.08%",
        "up": false,
        "c1": "#9AA3AD",
        "c2": "#4A5058",
        "classId": "crypto",
        "feed": "live",
        "mint": "Ga2AXHpqdfyDBFcefJit2Qm7GRhCPkTBQzFnkULRC2ZH"
      },
      {
        "sym": "DOGE",
        "name": "Dogecoin",
        "tag": "Perp",
        "px": "$0.1842",
        "chg": "+4.12%",
        "up": true,
        "c1": "#E0C36B",
        "c2": "#A5842A",
        "classId": "crypto",
        "feed": "live",
        "mint": "2wme8EVkw8qsfSk2B3QeX4S64ac6wxHPXb3GrdckEkio"
      },
      {
        "sym": "HYPE",
        "name": "Hyperliquid",
        "tag": "Spot · Perp",
        "px": "$40.96",
        "chg": "−1.20%",
        "up": false,
        "c1": "#49E39B",
        "c2": "#0E8F55",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "AAVE",
        "name": "Aave",
        "tag": "Spot · Perp",
        "px": "$291.03",
        "chg": "+3.10%",
        "up": true,
        "c1": "#B58CFF",
        "c2": "#6E3ED8",
        "classId": "crypto",
        "feed": "live",
        "mint": "3vAs4D1WE6Na4tCgt4BApgFfENbm8WY7q4cSPD1yM4Cg"
      },
      {
        "sym": "LINK",
        "name": "Chainlink",
        "tag": "Perp",
        "px": "$18.44",
        "chg": "+1.05%",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "crypto",
        "feed": "live",
        "mint": "CWE8jPTUYhdCTZYWPTe1o5DFqfdjzWKc9WKz6rSjQUdG"
      },
      {
        "sym": "TON",
        "name": "Toncoin",
        "tag": "Spot · Perp",
        "px": "$5.21",
        "chg": "−0.36%",
        "up": false,
        "c1": "#63C3F5",
        "c2": "#1D6FA8",
        "classId": "crypto",
        "feed": "live",
        "mint": "GEYrotdkRitGUK5UMv3aMttEhVAZLhRJMcG82zKYsaWB"
      }
    ]
  },
  {
    "id": "stocks",
    "label": "Stocks",
    "note": "Tokenized shares",
    "more": "All stocks",
    "instruments": [
      {
        "sym": "NVDAc",
        "name": "Nvidia",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#7CD64F",
        "c2": "#3D8B1E",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb20000000000000000000078ee7ce2fE4908108C"
      },
      {
        "sym": "AAPLc",
        "name": "Apple",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb200000000000000000000C2e324d24d7eEcd1fb"
      },
      {
        "sym": "TSLAc",
        "name": "Tesla",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000001e800a7f5189430cD0"
      },
      {
        "sym": "METAc",
        "name": "Meta",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000008bC8786B856E61707C"
      },
      {
        "sym": "MSFTc",
        "name": "Microsoft",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#63C3F5",
        "c2": "#1D6FA8",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xB200000000000000000000Ab99cFa739E253872B"
      },
      {
        "sym": "AMZNc",
        "name": "Amazon",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#F0BE55",
        "c2": "#B8791A",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb200000000000000000000d9192b6B456483C2E8"
      },
      {
        "sym": "GOOGLc",
        "name": "Alphabet",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FA9FF",
        "c2": "#2D57C4",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000002D0BA3164cc74f58B7"
      },
      {
        "sym": "MSTRc",
        "name": "MicroStrategy",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#F5A05A",
        "c2": "#B0561A",
        "classId": "stocks",
        "feed": "live",
        "mint": "0xb2000000000000000000004884b426556b92883d"
      }
    ]
  },
  {
    "id": "commodities",
    "label": "Commodities",
    "note": "Only gold has a price feed. None trade here yet.",
    "more": "All commodities",
    "instruments": [
      {
        "sym": "XAUT",
        "name": "Gold",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#F5CE5F",
        "c2": "#B98A0C",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "XAGT",
        "name": "Silver",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#D6DBE2",
        "c2": "#8C929B",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "CL",
        "name": "WTI Crude",
        "tag": "Perp · ICE feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#4A5058",
        "c2": "#1B1E22",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "BZ",
        "name": "Brent Crude",
        "tag": "Perp · ICE feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#5C6470",
        "c2": "#22262C",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "HG",
        "name": "Copper",
        "tag": "Perp · delivery ref",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E08B5A",
        "c2": "#9A4E22",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "PL",
        "name": "Platinum",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "PA",
        "name": "Palladium",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#B8BEC8",
        "c2": "#6A7078",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "NG",
        "name": "Natural Gas",
        "tag": "Perp · ICE feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FD6F5",
        "c2": "#1D7FA8",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "ZW",
        "name": "Wheat",
        "tag": "Perp · CBOT ref",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8C46B",
        "c2": "#A5822A",
        "classId": "commodities",
        "feed": "unavailable"
      }
    ]
  },
  {
    "id": "indices",
    "label": "Indices",
    "note": "No price feed. None trade here yet.",
    "more": "All indices",
    "instruments": [
      {
        "sym": "SPYx",
        "name": "S&P 500",
        "tag": "Spot · Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "QQQx",
        "name": "Nasdaq 100",
        "tag": "Spot · Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#B58CFF",
        "c2": "#7A45E0",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "IWMx",
        "name": "Russell 2000",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "DIAx",
        "name": "Dow 30",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FA9FF",
        "c2": "#2D57C4",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "EFAx",
        "name": "MSCI EAFE",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "GLDx",
        "name": "Gold ETF",
        "tag": "Spot · Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#F5CE5F",
        "c2": "#B98A0C",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "TLTx",
        "name": "20Y Treasury",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "HYGx",
        "name": "High Yield",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8A05A",
        "c2": "#B0561A",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "VIXx",
        "name": "Volatility",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "indices",
        "feed": "unavailable"
      }
    ]
  },
  {
    "id": "preipo",
    "label": "Pre-IPO",
    "note": "No price feed. Private companies have no token.",
    "more": "All pre-IPO",
    "instruments": [
      {
        "sym": "OPENAI",
        "name": "OpenAI",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "ANTHRP",
        "name": "Anthropic",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8A05A",
        "c2": "#B0561A",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "SPACEX",
        "name": "SpaceX",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#9AA3AD",
        "c2": "#3A4048",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "XAI",
        "name": "xAI",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#C9CDD4",
        "c2": "#5A6068",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "STRIPE",
        "name": "Stripe",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "DBRK",
        "name": "Databricks",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "PPLX",
        "name": "Perplexity",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "FIGMA",
        "name": "Figma",
        "tag": "Lists at IPO",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#B58CFF",
        "c2": "#7A45E0",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "CANVA",
        "name": "Canva",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FD6F5",
        "c2": "#1D7FA8",
        "classId": "preipo",
        "feed": "unavailable"
      }
    ]
  }
];
