/**
 * Was GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json. **Do not regenerate.**
 *
 * The generator's source is the design prototype's data and is stale in ways that break the app:
 * it has no token addresses, lists SPYx and QQQx as unfed indices, and carries Solana mints on the
 * crypto rows. The tokenized equities here are the eleven wrapped xStocks this project trades on
 * X Layer, each with its ERC-4626 wrapper address (`STOCKS` in server/src/venues/stocks.ts) — the
 * spelling `canonicalSymbol` and the whole equity path depend on. Running
 * `node tools/gen-fixtures.mjs` silently reverts them and takes the equities integration with it.
 *
 * Edit this file directly, and treat it as the source of truth it has become.
 *
 * Applied on the way through:
 *   G4  counts reconciled (45 total): 9 crypto, 11 stocks, 9 commodities, 7 indices, 9 pre-IPO; the 9th pre-IPO
 *       instrument added. SPYx and QQQx moved from indices to stocks when they became real xStocks on X Layer,
 *       and the unfed index placeholders lost their `x` (IWM, DIA, …): on X Layer a lowercase `x` marks a wrapped
 *       xStock (`isStockSymbol`), and an index nothing prices must not be asked of the share snapshot.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 *
 * NO PRICE IS STORED FOR AN INSTRUMENT NOTHING PRICES.
 *
 * The 27 instruments the catalog marks unfed — every commodity, index and pre-IPO name — used to carry the
 * design prototype's prices, shown under a SIMULATED tag: "OPENAI $164.20", "ANTHRP $121.55",
 * "SPACEX $402.70". Prices for companies that have no market, and change figures that also fed
 * the top-movers ranking, so a screen that sorts by "how far they moved" could list a move nobody
 * made. The tag satisfied the letter of "real or labelled" and not its intent — the same argument
 * this codebase already made about a live instrument whose feed times out, which shows a dash
 * rather than the design's price.
 *
 * So they keep what is genuinely catalog — symbol, name, venue tag, colours — and carry no
 * number. One of them still shows a price on screen, and correctly: CoinGecko prices tokenized gold,
 * so XAUT is given a real quote at runtime and stops being unfed. What it no longer has is a stored
 * number to fall back on when that quote does not come. `feed: 'unavailable'` on them means no feed backs this, and the UI says so.
 */
import type { AssetClass } from '../types';

export const assetClasses: AssetClass[] = [
  {
    "id": "crypto",
    "label": "Crypto",
    "note": "Spot prices, live",
    "more": "All crypto",
    "instruments": [
      {
        "sym": "BTC",
        "name": "Bitcoin",
        "tag": "Perp",
        "px": "$66,560",
        "chg": "+0.67%",
        "up": true,
        "c1": "#F7931A",
        "c2": "#B96908",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "ETH",
        "name": "Ethereum",
        "tag": "Perp",
        "px": "$2,443",
        "chg": "+2.11%",
        "up": true,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "SOL",
        "name": "Solana",
        "tag": "Spot · Perp",
        "px": "$88.32",
        "chg": "+2.40%",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#49E39B",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "XRP",
        "name": "XRP",
        "tag": "Perp",
        "px": "$2.94",
        "chg": "−1.08%",
        "up": false,
        "c1": "#9AA3AD",
        "c2": "#4A5058",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "DOGE",
        "name": "Dogecoin",
        "tag": "Perp",
        "px": "$0.1842",
        "chg": "+4.12%",
        "up": true,
        "c1": "#E0C36B",
        "c2": "#A5842A",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "HYPE",
        "name": "Hyperliquid",
        "tag": "Spot · Perp",
        "px": "$40.96",
        "chg": "−1.20%",
        "up": false,
        "c1": "#49E39B",
        "c2": "#0E8F55",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "AAVE",
        "name": "Aave",
        "tag": "Spot · Perp",
        "px": "$291.03",
        "chg": "+3.10%",
        "up": true,
        "c1": "#B58CFF",
        "c2": "#6E3ED8",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "LINK",
        "name": "Chainlink",
        "tag": "Perp",
        "px": "$18.44",
        "chg": "+1.05%",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "crypto",
        "feed": "live"
      },
      {
        "sym": "TON",
        "name": "Toncoin",
        "tag": "Spot · Perp",
        "px": "$5.21",
        "chg": "−0.36%",
        "up": false,
        "c1": "#63C3F5",
        "c2": "#1D6FA8",
        "classId": "crypto",
        "feed": "live"
      }
    ]
  },
  {
    "id": "stocks",
    "label": "Stocks",
    "note": "Tokenized shares",
    "more": "All stocks",
    "instruments": [
      {
        "sym": "NVDAx",
        "name": "Nvidia",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#7CD64F",
        "c2": "#3D8B1E",
        "classId": "stocks",
        "feed": "live",
        "address": "0xa8ddb5cd96b5222afe198316e9a57caa642850d5"
      },
      {
        "sym": "AAPLx",
        "name": "Apple",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "stocks",
        "feed": "live",
        "address": "0x943bf64d566c32a2bcd41ac92fb63c111cc9de8f"
      },
      {
        "sym": "TSLAx",
        "name": "Tesla",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "stocks",
        "feed": "live",
        "address": "0xc3fdbe3a68ee5de461d30415a8165cf9aefe1171"
      },
      {
        "sym": "METAx",
        "name": "Meta",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "stocks",
        "feed": "live",
        "address": "0xe840946ffebcd66b7c4e95095effafadfa0d0e56"
      },
      {
        "sym": "MSFTx",
        "name": "Microsoft",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#63C3F5",
        "c2": "#1D6FA8",
        "classId": "stocks",
        "feed": "live",
        "address": "0x166fbe68274b6a47e025f4ba17388c539f1fa1d0"
      },
      {
        "sym": "AMZNx",
        "name": "Amazon",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#F0BE55",
        "c2": "#B8791A",
        "classId": "stocks",
        "feed": "live",
        "address": "0x910cabde3eba7fc1ce64fd14bd680b9f60fa0f90"
      },
      {
        "sym": "GOOGLx",
        "name": "Alphabet",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FA9FF",
        "c2": "#2D57C4",
        "classId": "stocks",
        "feed": "live",
        "address": "0xf8c5308f80e459bb53d9ebe689854d9cbb2caa6f"
      },
      {
        "sym": "MSTRx",
        "name": "Strategy",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#F5A05A",
        "c2": "#B0561A",
        "classId": "stocks",
        "feed": "live",
        "address": "0x30987adf0b11dc698438a99ba04ec3a1ab2c7eab"
      },
      {
        "sym": "COINx",
        "name": "Coinbase",
        "tag": "Tokenized share",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#3A7BFF",
        "c2": "#1446C8",
        "classId": "stocks",
        "feed": "live",
        "address": "0x44c7ed7ffdf8465c9d27f60aec845eed3d49d56e"
      },
      {
        "sym": "SPYx",
        "name": "S&P 500 ETF",
        "tag": "Tokenized fund",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#5B93FF",
        "c2": "#1B44CE",
        "classId": "stocks",
        "feed": "live",
        "address": "0xe7e553cd128f0011777323a0b44a7b96ea1cb540"
      },
      {
        "sym": "QQQx",
        "name": "Nasdaq 100 ETF",
        "tag": "Tokenized fund",
        "px": "—",
        "chg": "",
        "up": true,
        "c1": "#B58CFF",
        "c2": "#7A45E0",
        "classId": "stocks",
        "feed": "live",
        "address": "0x4c1ae29c159838fc1b224636e28e086eb69101f7"
      }
    ]
  },
  {
    "id": "commodities",
    "label": "Commodities",
    "note": "Only gold has a price feed. None trade here yet.",
    "more": "All commodities",
    "instruments": [
      {
        "sym": "XAUT",
        "name": "Gold",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#F5CE5F",
        "c2": "#B98A0C",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "XAGT",
        "name": "Silver",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#D6DBE2",
        "c2": "#8C929B",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "CL",
        "name": "WTI Crude",
        "tag": "Perp · ICE feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#4A5058",
        "c2": "#1B1E22",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "BZ",
        "name": "Brent Crude",
        "tag": "Perp · ICE feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#5C6470",
        "c2": "#22262C",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "HG",
        "name": "Copper",
        "tag": "Perp · delivery ref",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E08B5A",
        "c2": "#9A4E22",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "PL",
        "name": "Platinum",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "PA",
        "name": "Palladium",
        "tag": "Perp · spot feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#B8BEC8",
        "c2": "#6A7078",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "NG",
        "name": "Natural Gas",
        "tag": "Perp · ICE feed",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FD6F5",
        "c2": "#1D7FA8",
        "classId": "commodities",
        "feed": "unavailable"
      },
      {
        "sym": "ZW",
        "name": "Wheat",
        "tag": "Perp · CBOT ref",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8C46B",
        "c2": "#A5822A",
        "classId": "commodities",
        "feed": "unavailable"
      }
    ]
  },
  {
    "id": "indices",
    "label": "Indices",
    "note": "No price feed. None trade here yet.",
    "more": "All indices",
    "instruments": [
      {
        "sym": "IWM",
        "name": "Russell 2000",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "DIA",
        "name": "Dow 30",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FA9FF",
        "c2": "#2D57C4",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "EFA",
        "name": "MSCI EAFE",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#C9CDD4",
        "c2": "#7A7F87",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "GLD",
        "name": "Gold ETF",
        "tag": "Spot · Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#F5CE5F",
        "c2": "#B98A0C",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "TLT",
        "name": "20Y Treasury",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "HYG",
        "name": "High Yield",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8A05A",
        "c2": "#B0561A",
        "classId": "indices",
        "feed": "unavailable"
      },
      {
        "sym": "VIX",
        "name": "Volatility",
        "tag": "Perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "indices",
        "feed": "unavailable"
      }
    ]
  },
  {
    "id": "preipo",
    "label": "Pre-IPO",
    "note": "No price feed. Private companies have no token.",
    "more": "All pre-IPO",
    "instruments": [
      {
        "sym": "OPENAI",
        "name": "OpenAI",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "ANTHRP",
        "name": "Anthropic",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8A05A",
        "c2": "#B0561A",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "SPACEX",
        "name": "SpaceX",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#9AA3AD",
        "c2": "#3A4048",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "XAI",
        "name": "xAI",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#C9CDD4",
        "c2": "#5A6068",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "STRIPE",
        "name": "Stripe",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#8FA6E8",
        "c2": "#4B5FA8",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "DBRK",
        "name": "Databricks",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#E8464B",
        "c2": "#98181C",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "PPLX",
        "name": "Perplexity",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#49E39B",
        "c2": "#12A45F",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "FIGMA",
        "name": "Figma",
        "tag": "Lists at IPO",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#B58CFF",
        "c2": "#7A45E0",
        "classId": "preipo",
        "feed": "unavailable"
      },
      {
        "sym": "CANVA",
        "name": "Canva",
        "tag": "Pre-IPO perp",
        "px": "—",
        "chg": "",
        "up": false,
        "c1": "#7FD6F5",
        "c2": "#1D7FA8",
        "classId": "preipo",
        "feed": "unavailable"
      }
    ]
  }
];
