/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 */
import type { NewsItem } from '../types';

export const newsFixtures: NewsItem[] = [
  {
    "id": "news-0",
    "tag": "MACRO",
    "t": "18m",
    "headline": "Fed holds, signals one more cut this year",
    "take": "Momentum Scout: risk-on. Raising crypto sleeve exposure to the top of your band.",
    "tagBg": "rgba(91,147,255,.16)",
    "tagFg": "#7FA9FF"
  },
  {
    "id": "news-1",
    "tag": "EARNINGS",
    "t": "2h",
    "headline": "NVDAx reports Thursday after the close",
    "take": "Earnings Desk: flattening the position Wednesday. Spread widens too much into prints.",
    "tagBg": "rgba(240,190,85,.16)",
    "tagFg": "#F0BE55"
  },
  {
    "id": "news-2",
    "tag": "ON-CHAIN",
    "t": "5h",
    "headline": "Aave supply rate on X Layer ticks up",
    "take": "Yield Keeper: moved $1,240 of idle cash in. Unlock is 3 days.",
    "tagBg": "rgba(73,227,155,.16)",
    "tagFg": "#49E39B"
  }
];
