/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 */
export const onboarding = {
  "goals": [
    "Grow long term",
    "Trade actively",
    "Earn yield",
    "Hedge my job",
    "Learn first"
  ],
  "riskLevels": [
    "Steady",
    "Balanced",
    "Aggressive"
  ],
  "kycSteps": [
    {
      "label": "Phone verified",
      "detail": "+1 ••• ••• 4417"
    },
    {
      "label": "Photo ID",
      "detail": "Front and back, well lit"
    },
    {
      "label": "Liveness check",
      "detail": "A short selfie video"
    },
    {
      "label": "Funding source",
      "detail": "Bank or card"
    }
  ],
  "fundingMethods": [
    {
      "name": "Bank transfer",
      "detail": "Free · lands in 1–2 days",
      "tag": "Free",
      "feePct": 0,
      "lands": "Tue, Sep 8"
    },
    {
      "name": "Debit card",
      "detail": "Instant · 1.5% fee",
      "tag": "Instant",
      "feePct": 1.5,
      "lands": "Right away"
    },
    {
      "name": "Send crypto",
      "detail": "USDC, USDT0 or OKB on X Layer",
      "tag": "On-chain",
      "feePct": 0,
      "lands": "After 1 confirmation"
    }
  ],
  "depositPresets": [
    250,
    500,
    1000,
    2500
  ]
} as const;

export const agentControls = {
  "runFor": [
    "1 Day",
    "3 Days",
    "7 Days",
    "30 Days"
  ],
  "riskLevels": [
    "Low",
    "Medium",
    "High"
  ],
  "spendCap": {
    "min": 200,
    "max": 5000,
    "step": 200,
    "default": 1600
  }
} as const;
