/**
 * GENERATED by tools/gen-fixtures.mjs from ui/mobile-ui/data/markets.json — do not edit by hand.
 *
 * Applied on the way through:
 *   G4  counts reconciled to 9 per class (45 total); the 9th pre-IPO instrument added.
 *   G12 every numeric field normalised to U+2212.
 *   feed: 'live' | 'unavailable' stamped per class, so the UI can say when nothing prices an instrument.
 */
import type { Bar, WatchlistGroup } from '../types';

/**
 * G5: sparkline polylines, lifted out of the prototype's inline `data` object.
 *
 * Read by no screen. The watchlist presented these symbols as a list someone had chosen; it lists
 * `/market/watchable` now. They stay only because `fixtures.test.ts` still checks their shape.
 */
export const watchlistGroups: WatchlistGroup[] = [
  {
    "label": "Tokens",
    "tab": "Conviction List",
    "rows": [
      {
        "sym": "TSLAc",
        "px": "—",
        "chg": "",
        "up": true,
        "spark": "0,22 12,18 24,20 36,12 48,15 60,8 72,11 90,4"
      },
      {
        "sym": "SOL",
        "px": "—",
        "chg": "",
        "up": true,
        "spark": "0,20 14,14 26,17 38,9 52,13 66,7 78,10 90,5"
      },
      {
        "sym": "HYPE",
        "px": "—",
        "chg": "",
        "up": false,
        "spark": "0,8 14,12 28,10 40,17 54,14 68,20 80,18 90,24"
      }
    ]
  },
  {
    "label": "Equities",
    "tab": "Stocks",
    "rows": [
      {
        "sym": "NVDAc",
        "px": "—",
        "chg": "",
        "up": true,
        "spark": "0,24 14,19 28,21 42,13 56,15 72,8 90,5"
      },
      {
        "sym": "AAPLc",
        "px": "—",
        "chg": "",
        "up": true,
        "spark": "0,17 16,15 32,16 48,13 64,14 78,11 90,12"
      },
      {
        "sym": "MSTRc",
        "px": "—",
        "chg": "",
        "up": false,
        "spark": "0,7 16,11 30,9 44,15 60,17 76,16 90,23"
      }
    ]
  },
  {
    "label": "Protocols",
    "tab": "Defi",
    "rows": [
      {
        "sym": "AAVE",
        "px": "—",
        "chg": "",
        "up": true,
        "spark": "0,25 14,20 30,22 46,12 62,14 78,7 90,4"
      }
    ]
  }
];

/** G7: area-chart geometry, lifted out of hardcoded SVG point strings. */
export const areaSeries: Record<string, string> = {
  "XAUT": "0,84 30,78 60,82 92,64 124,70 156,52 188,58 220,42 252,48 284,32 316,38 360,24",
  "SOL": "0,92 32,86 64,88 96,72 128,76 160,60 192,66 224,50 256,54 288,38 320,42 360,26"
};

/** The 12 hourly BTC/USD bars shared by screens 21 and 6. design.md §6. */
export const btcBars: Bar[] = [[66120,66480,66020,66400],[66400,66520,66180,66240],[66240,66300,65860,65920],[65920,66040,65600,65700],[65700,65780,65380,65460],[65460,65540,65180,65240],[65240,65700,65200,65640],[65640,65720,65420,65480],[65480,65960,65440,65900],[65900,66140,65840,66080],[66080,66360,66020,66300],[66300,66620,66240,66560]];
